# Generated by Django 4.2.20 on 2025-03-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
