# Generated by Django 4.2.20 on 2025-03-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_patient_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="neuralnetqueue",
            name="queue_id",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
