# Generated by Django 4.2.20 on 2025-04-08 08:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedstatData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("research_key", models.CharField(max_length=100, unique=True)),
                ("history_number", models.CharField(max_length=100)),
                ("fullname", models.CharField(max_length=100)),
                ("patient_result", models.JSONField()),
                ("gender", models.CharField(max_length=10)),
                ("research_date", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "medstat_data",
            },
        ),
        migrations.CreateModel(
            name="NeuralNetQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue_number", models.PositiveIntegerField(unique=True)),
                ("research_key", models.CharField(max_length=100)),
                ("history_number", models.CharField(max_length=100)),
                ("result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_data", models.JSONField()),
                ("research_key", models.CharField(max_length=100)),
                ("history_number", models.CharField(max_length=100)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "queue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db2app.neuralnetqueue",
                    ),
                ),
            ],
        ),
    ]
