# Generated by Django 4.2.20 on 2025-04-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedstatData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("research_key", models.CharField(max_length=100, unique=True)),
                ("patient_result", models.JSONField()),
                ("gender", models.CharField(max_length=10)),
                ("research_date", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "RESEARCHES",
                "managed": False,
            },
        ),
    ]
